{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE MultiWayIf #-}
{-# LANGUAGE RankNTypes #-}
module Brick.Widgets.Menu
  ( MenuItem(..)
  , MenuRegion(..)

  , Menu(..)
  , menuTitleL
  , menuItemsL
  , menuIsOpenL
  , menuWidthL
  , menuRegionNameBuilderL
  , menuSelectedIndexL
  , menuEventHandlerL

  , MenuEntry(..)
  , menuEntryTitleL
  , menuEntryEnabledL
  , menuEntryEventL

  , menu
  , menuSeparator
  , menuGap
  , menuEntry
  , renderMenu

  -- * Alternative use cases
  , SimpleMenu
  , simpleMenu

  -- * Handling events
  , handleMenuEvent

  -- * Attributes
  , menuAttr
  , menuTitleAttr
  , menuTitleSelectedAttr
  , menuBodyAttr
  , menuEntryDisabledAttr
  , menuEntrySelectedAttr
  , menuEntrySelectedDisabledAttr
  )
where

import Lens.Micro ((^.), (.~), (&), Lens')
import Lens.Micro.Mtl

import qualified Data.Text as T
import qualified Data.Vector as V

import qualified Graphics.Vty as Vty

import Brick.AttrMap
import Brick.Types
import Brick.Widgets.Border
import Brick.Widgets.Core

-- | The type of menu regions, for embedding in the application's
-- resource name and reporting mouse click events.
data MenuRegion =
    MenuTitle
    -- ^ The region of a menu's title
    | MenuBody
    -- ^ The region of a menu's body
    deriving (Ord, Show, Eq)

data Menu s n k =
    Menu { menuTitle :: T.Text
         -- ^ The menu's title
         , menuItems :: V.Vector (MenuItem s k)
         -- ^ The contents of the menu
         , menuIsOpen :: Bool
         -- ^ Whether the menu is showing
         , menuWidth :: Int
         -- ^ The width of the menu's items within the enclosing border
         , menuRegionNameBuilder :: MenuRegion -> n
         -- ^ A function to build resource names for clickable regions
         , menuSelectedIndex :: Maybe Int
         -- ^ State for tracking the selected item index, if any
         , menuEventHandler :: k -> EventM n s ()
         -- ^ Handler for events generated by this menu
         }

data MenuItem s k =
    MISeparator
    -- ^ A horizontal border between menu items
    | MIGap
    -- ^ An empty line between menu items
    | MIEntry (MenuEntry s k)
    -- ^ A menu entry

data MenuEntry s k =
    MenuEntry { menuEntryTitle :: T.Text
              -- ^ The menu entry's title
              , menuEntryEnabled :: s -> Bool
              -- ^ The function to determine whether this menu entry is
              -- enabled
              , menuEntryEvent :: k
              -- ^ The event to generate when this entry is activated
              }

suffixLenses ''Menu
suffixLenses ''MenuEntry

menuSeparator :: MenuItem s n
menuSeparator = MISeparator

menuGap :: MenuItem s n
menuGap = MIGap

menuEntry :: T.Text -> (s -> Bool) -> k -> MenuItem s k
menuEntry title enabled ev = MIEntry $ MenuEntry title enabled ev

type SimpleMenu s n = Menu s n (EventM n s ())

simpleMenu :: T.Text -> (MenuRegion -> n) -> [MenuItem s (EventM n s ())] -> SimpleMenu s n
simpleMenu title regionNameBuilder items =
    menu title regionNameBuilder items id

menu :: T.Text -> (MenuRegion -> n) -> [MenuItem s k] -> (k -> EventM n s ()) -> Menu s n k
menu title regionNameBuilder items handler =
    let defaultWidth = (maximum $ menuItemWidth <$> items) + 3
    in Menu { menuTitle = title
            , menuItems = V.fromList items
            , menuIsOpen = False
            , menuWidth = defaultWidth
            , menuRegionNameBuilder = regionNameBuilder
            , menuSelectedIndex = Nothing
            , menuEventHandler = handler
            }

menuItemWidth :: MenuItem s k -> Int
menuItemWidth MISeparator = 0
menuItemWidth MIGap = 0
menuItemWidth (MIEntry e) = menuEntryWidth e

menuEntryWidth :: MenuEntry s k -> Int
menuEntryWidth = textWidth . menuEntryTitle

renderMenu :: (Ord n) => s -> Menu s n k -> Widget n
renderMenu s m =
    if menuIsOpen m
    then (translateLayer (Location (0, 1)) body) `above` title
    else title
    where
        setTitleAttr = if menuIsOpen m
                       then withDefAttr menuTitleSelectedAttr
                       else withDefAttr menuTitleAttr
        title = clickable (menuRegionNameBuilder m MenuTitle) $
                setTitleAttr $
                txt $ menuTitle m

        body = joinBorders $
               border $
               hLimit (menuWidth m) $
               clickable (menuRegionNameBuilder m MenuBody) $
               vBox $
               renderMenuItem <$> (zip [0..] $ V.toList $ menuItems m)

        renderMenuItem (_, MISeparator) = hBorder
        renderMenuItem (_, MIGap)       = vLimit 1 $ fill ' '
        renderMenuItem (i, MIEntry e)   = renderMenuEntry i e

        renderMenuEntry i e =
            setEntryAttr i e $
            vLimit 1 $
            padRight Max $
            txt $ menuEntryTitle e

        setEntryAttr i e =
            if Just i == menuSelectedIndex m
            then if menuEntryEnabled e s
                 then withDefAttr menuEntrySelectedAttr
                 else withDefAttr menuEntrySelectedDisabledAttr
            else if menuEntryEnabled e s
                 then id
                 else withDefAttr menuEntryDisabledAttr

menuAttr :: AttrName
menuAttr = attrName "brick" <> attrName "menu"

menuTitleAttr :: AttrName
menuTitleAttr = menuAttr <> attrName "title"

menuTitleSelectedAttr :: AttrName
menuTitleSelectedAttr = menuTitleAttr <> attrName "selected"

menuBodyAttr :: AttrName
menuBodyAttr = menuAttr <> attrName "body"

menuEntryDisabledAttr :: AttrName
menuEntryDisabledAttr = menuBodyAttr <> attrName "disabled"

menuEntrySelectedAttr :: AttrName
menuEntrySelectedAttr = menuBodyAttr <> attrName "selected"

menuEntrySelectedDisabledAttr :: AttrName
menuEntrySelectedDisabledAttr = menuEntrySelectedAttr <> attrName "disabled"

selectNextEntry :: Menu s n k -> Menu s n k
selectNextEntry m =
    case matching V.!? 0 of
        Nothing -> m
        Just (newIdx, _) -> m & menuSelectedIndexL .~ Just newIdx
    where
        dropAmt = case m^.menuSelectedIndexL of
                 Nothing -> 0
                 Just i -> i + 1
        is = m^.menuItemsL
        matching = V.filter (isEntry . snd) items
        pairs = V.zip (V.enumFromN 0 (V.length is)) is
        items = V.drop dropAmt $ pairs <> pairs
        isEntry (MIEntry {}) = True
        isEntry _ = False

selectPrevEntry :: Menu s n k -> Menu s n k
selectPrevEntry m =
    case matching V.!? 0 of
        Nothing -> m
        Just (newIdx, _) -> m & menuSelectedIndexL .~ Just newIdx
    where
        takeAmt = case m^.menuSelectedIndexL of
                 Nothing -> 0
                 Just i -> i
        is = m^.menuItemsL
        matching = V.filter (isEntry . snd) items
        pairs = V.zip (V.enumFromN 0 (V.length is)) is
        items = V.reverse $ pairs <> V.take takeAmt pairs
        isEntry (MIEntry {}) = True
        isEntry _ = False

handleMenuEvent :: (Eq n) => Lens' s (Menu s n k) -> BrickEvent n e -> EventM n s ()
handleMenuEvent which (VtyEvent (Vty.EvKey Vty.KEnter [])) = do
    sel <- use (which.menuSelectedIndexL)
    handler <- use (which.menuEventHandlerL)
    is <- use (which.menuItemsL)
    case sel of
        Nothing -> return ()
        Just idx ->
            case is V.!? idx of
                Just (MIEntry entry) -> do
                    which.menuIsOpenL %= not
                    handler $ menuEntryEvent entry
                _ -> return ()
handleMenuEvent which (VtyEvent (Vty.EvKey Vty.KDown [])) =
    which %= selectNextEntry
handleMenuEvent which (VtyEvent (Vty.EvKey Vty.KUp [])) = do
    which %= selectPrevEntry
handleMenuEvent which (MouseDown n _ _ (Location (_, row))) = do
    mkRegionName <- use (which.menuRegionNameBuilderL)
    if | mkRegionName MenuTitle == n ->
           which.menuIsOpenL %= not
       | mkRegionName MenuBody == n -> do
           -- Map the location to the clicked menu entry
           is <- use (which.menuItemsL)
           handler <- use (which.menuEventHandlerL)
           case is V.!? row of
               Just (MIEntry entry) -> do
                   which.menuIsOpenL %= not
                   handler $ menuEntryEvent entry
               _ -> return ()
       | otherwise -> return ()
handleMenuEvent which (VtyEvent (Vty.EvMouseDown {})) =
    which.menuIsOpenL %= not
handleMenuEvent which (VtyEvent (Vty.EvKey Vty.KEsc [])) =
    -- Esc closes the menu
    which.menuIsOpenL %= not
handleMenuEvent _ _ =
    return ()
